// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Model.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260329153041_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Model.Entities.AnimalCat", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<int>("Flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("flag");

                    b.Property<bool>("LovesBox")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("loves_box");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double>("WhiskerLength")
                        .HasColumnType("double precision")
                        .HasColumnName("whisker_length")
                        .HasComment("鬍鬚長度");

                    b.HasKey("Id")
                        .HasName("p_animal_cat");

                    b.ToTable("animal_cat", null, t =>
                        {
                            t.HasComment("AnimalCat");
                        });
                });

            modelBuilder.Entity("Model.Entities.AnimalDog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("breed");

                    b.Property<int>("Flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("flag");

                    b.Property<bool>("IsGoodBoy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_good_boy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_animal_dog");

                    b.ToTable("animal_dog", null, t =>
                        {
                            t.HasComment("AnimalDog");
                        });
                });

            modelBuilder.Entity("Model.Entities.AppIndex", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("C1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("text")
                        .HasDefaultValue("C1")
                        .HasColumnName("c1");

                    b.Property<string>("C2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasDefaultValue("C2")
                        .HasColumnName("c2");

                    b.HasKey("Id")
                        .HasName("p_app_index");

                    b.HasIndex("C1")
                        .IsUnique()
                        .HasDatabaseName("i_app_index_4d1f45");

                    b.HasIndex("C1", "C2")
                        .HasDatabaseName("i_app_index_d3bba8");

                    b.ToTable("app_index", null, t =>
                        {
                            t.HasComment("AppIndex");
                        });
                });

            modelBuilder.Entity("Model.Entities.AppTable", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnyJsonString")
                        .HasColumnType("jsonb")
                        .HasColumnName("any_json_string");

                    b.Property<DateOnly?>("DateOnly")
                        .HasColumnType("date")
                        .HasColumnName("date_only");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time");

                    b.Property<DateTimeOffset?>("DateTimeOffset")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_offset");

                    b.Property<decimal?>("Decimal")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("decimal");

                    b.Property<int?>("Enum")
                        .HasColumnType("integer")
                        .HasColumnName("enum");

                    b.Property<int?>("Int")
                        .HasColumnType("integer")
                        .HasColumnName("int");

                    b.Property<long?>("Long")
                        .HasColumnType("bigint")
                        .HasColumnName("long");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("String")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("string");

                    b.PrimitiveCollection<List<string>>("StringJsonObjects")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("string_json_objects");

                    b.Property<string>("ValueJsonObject")
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json_object");

                    b.Property<string>("ValueJsonObjects")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json_objects");

                    b.HasKey("Id")
                        .HasName("p_app_table");

                    b.HasAlternateKey("String")
                        .HasName("a_app_table_274c57");

                    b.HasIndex("String")
                        .IsUnique()
                        .HasDatabaseName("i_app_table_274c57")
                        .HasFilter("string IS NOT NULL");

                    b.HasIndex("StringJsonObjects")
                        .HasDatabaseName("i_app_table_a58f81");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("StringJsonObjects"), "gin");

                    b.HasIndex("ValueJsonObject")
                        .HasDatabaseName("i_app_table_bc7bf3");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ValueJsonObject"), "gin");

                    b.HasIndex("ValueJsonObjects")
                        .HasDatabaseName("i_app_table_36bbf3");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ValueJsonObjects"), "gin");

                    b.ToTable("app_table", null, t =>
                        {
                            t.HasComment("AppTable");

                            t.HasCheckConstraint("c_app_table_d5e7b8", "int > 0");
                        });
                });

            modelBuilder.Entity("Model.Entities.AspRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("p_asp_role");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("i_asp_role_51e4ef");

                    b.ToTable("asp_role", (string)null);
                });

            modelBuilder.Entity("Model.Entities.AspRoleClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(1024)
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("p_asp_role_claim");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("i_asp_role_claim_69fd8d");

                    b.ToTable("asp_role_claim", (string)null);
                });

            modelBuilder.Entity("Model.Entities.AspUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("p_asp_user");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("i_asp_user_2182de");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("i_asp_user_2004df");

                    b.ToTable("asp_user", (string)null);
                });

            modelBuilder.Entity("Model.Entities.AspUserClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasMaxLength(1024)
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_asp_user_claim");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_asp_user_claim_8934e3");

                    b.ToTable("asp_user_claim", (string)null);
                });

            modelBuilder.Entity("Model.Entities.AspUserLogin", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("p_asp_user_login");

                    b.HasIndex("UserId")
                        .HasDatabaseName("i_asp_user_login_8934e3");

                    b.ToTable("asp_user_login", (string)null);
                });

            modelBuilder.Entity("Model.Entities.AspUserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("p_asp_user_role");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("i_asp_user_role_69fd8d");

                    b.ToTable("asp_user_role", (string)null);
                });

            modelBuilder.Entity("Model.Entities.AspUserToken", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasMaxLength(2048)
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("p_asp_user_token");

                    b.ToTable("asp_user_token", (string)null);
                });

            modelBuilder.Entity("Model.Entities.ClosureNode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_closure_node");

                    b.ToTable("closure_node", null, t =>
                        {
                            t.HasComment("ClosureNode");
                        });
                });

            modelBuilder.Entity("Model.Entities.ClosurePath", b =>
                {
                    b.Property<Guid>("AncestorId")
                        .HasColumnType("uuid")
                        .HasColumnName("ancestor_id");

                    b.Property<Guid>("DescendantId")
                        .HasColumnType("uuid")
                        .HasColumnName("descendant_id");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.HasKey("AncestorId", "DescendantId")
                        .HasName("p_closure_path");

                    b.HasIndex("DescendantId")
                        .HasDatabaseName("i_closure_path_b1e295");

                    b.ToTable("closure_path", null, t =>
                        {
                            t.HasComment("ClosurePath");
                        });
                });

            modelBuilder.Entity("Model.Entities.FamilyChild1", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("updated_at");

                    b.HasKey("Id")
                        .HasName("p_family_child1");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("i_family_child1_6fa56f");

                    b.ToTable("family_child1", null, t =>
                        {
                            t.HasComment("FamilyChild1");
                        });
                });

            modelBuilder.Entity("Model.Entities.FamilyChild2", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("updated_at");

                    b.HasKey("Id")
                        .HasName("p_family_child2");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("i_family_child2_6fa56f");

                    b.ToTable("family_child2", null, t =>
                        {
                            t.HasComment("FamilyChild2");
                        });
                });

            modelBuilder.Entity("Model.Entities.FamilyParent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasComment("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasComment("updated_at");

                    b.HasKey("Id")
                        .HasName("p_family_parent");

                    b.ToTable("family_parent", null, t =>
                        {
                            t.HasComment("FamilyParent");
                        });
                });

            modelBuilder.Entity("Model.Entities.HumanBody", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_date");

                    b.Property<int>("Color")
                        .HasColumnType("integer")
                        .HasColumnName("color");

                    b.Property<Guid?>("HeadId")
                        .HasColumnType("uuid")
                        .HasColumnName("head_id");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<string>("Ulid")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("ulid");

                    b.Property<int>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("p_human_body");

                    b.HasIndex("HeadId")
                        .IsUnique()
                        .HasDatabaseName("i_human_body_0d4caa");

                    b.ToTable("human_body", null, t =>
                        {
                            t.HasComment("HumanBody");
                        });
                });

            modelBuilder.Entity("Model.Entities.HumanHead", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_date");

                    b.Property<int>("Color")
                        .HasColumnType("integer")
                        .HasColumnName("color");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<string>("Ulid")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("ulid");

                    b.Property<int>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("p_human_head");

                    b.ToTable("human_head", null, t =>
                        {
                            t.HasComment("HumanHead");
                        });
                });

            modelBuilder.Entity("Model.Entities.HumanLimb", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BodyId")
                        .HasColumnType("uuid")
                        .HasColumnName("body_id");

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_date");

                    b.Property<int>("Color")
                        .HasColumnType("integer")
                        .HasColumnName("color");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<string>("Ulid")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("text")
                        .HasColumnName("ulid");

                    b.Property<int>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("p_human_limb");

                    b.HasIndex("BodyId")
                        .HasDatabaseName("i_human_limb_394eba");

                    b.ToTable("human_limb", null, t =>
                        {
                            t.HasComment("HumanLimb");
                        });
                });

            modelBuilder.Entity("Model.Entities.LinkFirstContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_link_first_content");

                    b.ToTable("link_first_content", null, t =>
                        {
                            t.HasComment("LinkFirstContent");
                        });
                });

            modelBuilder.Entity("Model.Entities.LinkSecondContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_link_second_content");

                    b.ToTable("link_second_content", null, t =>
                        {
                            t.HasComment("LinkSecondContent");
                        });
                });

            modelBuilder.Entity("Model.Entities.LinkSubContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("LinkType")
                        .HasColumnType("integer")
                        .HasColumnName("link_type");

                    b.HasKey("Id")
                        .HasName("p_link_sub_content");

                    b.ToTable("link_sub_content", null, t =>
                        {
                            t.HasComment("LinkSubContent");
                        });

                    b.HasDiscriminator<int>("LinkType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Model.Entities.SubjectContent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("integer")
                        .HasColumnName("reference_type");

                    b.HasKey("Id")
                        .HasName("p_subject_content");

                    b.HasIndex("ReferenceId", "ReferenceType")
                        .HasDatabaseName("i_subject_content_416b18");

                    b.ToTable("subject_content", (string)null);

                    b.HasDiscriminator<int>("ReferenceType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Model.Entities.SubjectFirst", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_subject_first");

                    b.ToTable("subject_first", null, t =>
                        {
                            t.HasComment("SubjectFirst");
                        });
                });

            modelBuilder.Entity("Model.Entities.SubjectSecond", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_subject_second");

                    b.ToTable("subject_second", null, t =>
                        {
                            t.HasComment("SubjectSecond");
                        });
                });

            modelBuilder.Entity("Model.Entities.VehicleBase", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("VehicleCarType")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_car_type");

                    b.HasKey("Id")
                        .HasName("p_vehicle_base");

                    b.HasIndex("Type")
                        .HasDatabaseName("i_vehicle_base_682a0e");

                    b.ToTable("vehicle_base", null, t =>
                        {
                            t.HasCheckConstraint("c_vehicle_base_cb4012", "Type IN (1, 2)");
                        });

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Model.Queries.EmptyDbSet", b =>
                {
                    b.ToTable("empty_db_set", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Model.Queries.FuncTableResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_func_table_result");

                    b.ToTable((string)null);

                    b.ToFunction("func_table");
                });

            modelBuilder.Entity("Model.Queries.FuncTableWithParamResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_func_table_with_param_result");

                    b.ToTable((string)null);

                    b.ToFunction("func_table_with_param");
                });

            modelBuilder.Entity("Model.Queries.KeyLessResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.ToTable("key_less_result", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Model.Queries.ViewResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_view_result");

                    b.ToTable((string)null);

                    b.ToView("view", (string)null);
                });

            modelBuilder.Entity("rel_link_first_sub_content", b =>
                {
                    b.Property<Guid>("link_first_content_id")
                        .HasColumnType("uuid")
                        .HasColumnName("link_first_content_id");

                    b.Property<Guid>("link_sub_content_id")
                        .HasColumnType("uuid")
                        .HasColumnName("link_sub_content_id");

                    b.HasKey("link_first_content_id", "link_sub_content_id")
                        .HasName("p_rel_link_first_sub_content");

                    b.HasIndex("link_sub_content_id")
                        .HasDatabaseName("i_rel_link_first_sub_content_d5f4dd");

                    b.ToTable("rel_link_first_sub_content", (string)null);
                });

            modelBuilder.Entity("rel_link_second_sub_content", b =>
                {
                    b.Property<Guid>("link_second_content_id")
                        .HasColumnType("uuid")
                        .HasColumnName("link_second_content_id");

                    b.Property<Guid>("link_sub_content_id")
                        .HasColumnType("uuid")
                        .HasColumnName("link_sub_content_id");

                    b.HasKey("link_second_content_id", "link_sub_content_id")
                        .HasName("p_rel_link_second_sub_content");

                    b.HasIndex("link_sub_content_id")
                        .HasDatabaseName("i_rel_link_second_sub_content_d5f4dd");

                    b.ToTable("rel_link_second_sub_content", (string)null);
                });

            modelBuilder.Entity("Model.Entities.LinkFirstSubContent", b =>
                {
                    b.HasBaseType("Model.Entities.LinkSubContent");

                    b.Property<string>("First")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Model.Entities.LinkSecondSubContent", b =>
                {
                    b.HasBaseType("Model.Entities.LinkSubContent");

                    b.Property<string>("Second")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("second");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Model.Entities.SubjectFirstContent", b =>
                {
                    b.HasBaseType("Model.Entities.SubjectContent");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Model.Entities.SubjectSecondContent", b =>
                {
                    b.HasBaseType("Model.Entities.SubjectContent");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Model.Entities.VehicleLargeCar", b =>
                {
                    b.HasBaseType("Model.Entities.VehicleBase");

                    b.Property<string>("CarName")
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("car_name");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("LargeCarName")
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("large_car_name");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("c_vehicle_base_cb4012", "Type IN (1, 2)");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Model.Entities.VehicleSmallCar", b =>
                {
                    b.HasBaseType("Model.Entities.VehicleBase");

                    b.Property<string>("CarName")
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("car_name");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("SmallCarName")
                        .HasMaxLength(50)
                        .HasColumnType("text")
                        .HasColumnName("small_car_name");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("c_vehicle_base_cb4012", "Type IN (1, 2)");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Model.Entities.AspRoleClaim", b =>
                {
                    b.HasOne("Model.Entities.AspRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_asp_role_claim_69fd8d");
                });

            modelBuilder.Entity("Model.Entities.AspUserClaim", b =>
                {
                    b.HasOne("Model.Entities.AspUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_asp_user_claim_8934e3");
                });

            modelBuilder.Entity("Model.Entities.AspUserLogin", b =>
                {
                    b.HasOne("Model.Entities.AspUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_asp_user_login_8934e3");
                });

            modelBuilder.Entity("Model.Entities.AspUserRole", b =>
                {
                    b.HasOne("Model.Entities.AspRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_asp_user_role_69fd8d");

                    b.HasOne("Model.Entities.AspUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_asp_user_role_8934e3");
                });

            modelBuilder.Entity("Model.Entities.AspUserToken", b =>
                {
                    b.HasOne("Model.Entities.AspUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_asp_user_token_8934e3");
                });

            modelBuilder.Entity("Model.Entities.ClosurePath", b =>
                {
                    b.HasOne("Model.Entities.ClosureNode", "Ancestor")
                        .WithMany("DescendantPaths")
                        .HasForeignKey("AncestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_closure_path_e210a0");

                    b.HasOne("Model.Entities.ClosureNode", "Descendant")
                        .WithMany("AncestorPaths")
                        .HasForeignKey("DescendantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_closure_path_b1e295");

                    b.Navigation("Ancestor");

                    b.Navigation("Descendant");
                });

            modelBuilder.Entity("Model.Entities.FamilyChild1", b =>
                {
                    b.HasOne("Model.Entities.FamilyParent", "FamilyParent")
                        .WithMany("FamilyChild1")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_family_child1_6fa56f");

                    b.Navigation("FamilyParent");
                });

            modelBuilder.Entity("Model.Entities.FamilyChild2", b =>
                {
                    b.HasOne("Model.Entities.FamilyParent", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_family_child2_6fa56f");
                });

            modelBuilder.Entity("Model.Entities.HumanBody", b =>
                {
                    b.HasOne("Model.Entities.HumanHead", "HumanHead")
                        .WithOne("HumanBody")
                        .HasForeignKey("Model.Entities.HumanBody", "HeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_human_body_0d4caa");

                    b.Navigation("HumanHead");
                });

            modelBuilder.Entity("Model.Entities.HumanLimb", b =>
                {
                    b.HasOne("Model.Entities.HumanBody", "HumanBody")
                        .WithMany("HumanLimbs")
                        .HasForeignKey("BodyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_human_limb_394eba");

                    b.Navigation("HumanBody");
                });

            modelBuilder.Entity("Model.Queries.FuncTableResult", b =>
                {
                    b.HasOne("Model.Entities.AnimalCat", null)
                        .WithOne("FuncTableResult")
                        .HasForeignKey("Model.Queries.FuncTableResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_func_table_result_animal_cat_id");
                });

            modelBuilder.Entity("Model.Queries.ViewResult", b =>
                {
                    b.HasOne("Model.Entities.AnimalCat", null)
                        .WithOne("ViewResult")
                        .HasForeignKey("Model.Queries.ViewResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_view_result_animal_cat_id");
                });

            modelBuilder.Entity("rel_link_first_sub_content", b =>
                {
                    b.HasOne("Model.Entities.LinkFirstContent", null)
                        .WithMany()
                        .HasForeignKey("link_first_content_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_rel_link_first_sub_content_9c6c37");

                    b.HasOne("Model.Entities.LinkFirstSubContent", null)
                        .WithMany()
                        .HasForeignKey("link_sub_content_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_rel_link_first_sub_content_d5f4dd");
                });

            modelBuilder.Entity("rel_link_second_sub_content", b =>
                {
                    b.HasOne("Model.Entities.LinkSecondContent", null)
                        .WithMany()
                        .HasForeignKey("link_second_content_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_rel_link_second_sub_content_8fa616");

                    b.HasOne("Model.Entities.LinkSecondSubContent", null)
                        .WithMany()
                        .HasForeignKey("link_sub_content_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_rel_link_second_sub_content_d5f4dd");
                });

            modelBuilder.Entity("Model.Entities.SubjectFirstContent", b =>
                {
                    b.HasOne("Model.Entities.SubjectFirst", "Subject")
                        .WithMany("Contents")
                        .HasForeignKey("ReferenceId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("d_subject_first_content_3cc620");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Model.Entities.SubjectSecondContent", b =>
                {
                    b.HasOne("Model.Entities.SubjectSecond", "Subject")
                        .WithMany("Contents")
                        .HasForeignKey("ReferenceId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("d_subject_second_content_3cc620");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Model.Entities.AnimalCat", b =>
                {
                    b.Navigation("FuncTableResult")
                        .IsRequired();

                    b.Navigation("ViewResult")
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Entities.ClosureNode", b =>
                {
                    b.Navigation("AncestorPaths");

                    b.Navigation("DescendantPaths");
                });

            modelBuilder.Entity("Model.Entities.FamilyParent", b =>
                {
                    b.Navigation("FamilyChild1");
                });

            modelBuilder.Entity("Model.Entities.HumanBody", b =>
                {
                    b.Navigation("HumanLimbs");
                });

            modelBuilder.Entity("Model.Entities.HumanHead", b =>
                {
                    b.Navigation("HumanBody")
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Entities.SubjectFirst", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("Model.Entities.SubjectSecond", b =>
                {
                    b.Navigation("Contents");
                });
#pragma warning restore 612, 618
        }
    }
}
