// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Model.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Model.Entities.AnimalCat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<int>("Flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("flag");

                    b.Property<bool>("LovesBox")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("loves_box");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<double>("WhiskerLength")
                        .HasColumnType("double precision")
                        .HasColumnName("whisker_length")
                        .HasComment("鬍鬚長度");

                    b.HasKey("Id")
                        .HasName("p_animal_cat");

                    b.ToTable("animal_cat", null, t =>
                        {
                            t.HasComment("AnimalCat");
                        });
                });

            modelBuilder.Entity("Model.Entities.AnimalDog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birth_date");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("breed");

                    b.Property<int>("Flag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("flag");

                    b.Property<bool>("IsGoodBoy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_good_boy");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_animal_dog");

                    b.ToTable("animal_dog", null, t =>
                        {
                            t.HasComment("AnimalDog");
                        });
                });

            modelBuilder.Entity("Model.Entities.AppIndex", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("C1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .IsUnicode(true)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("C1")
                        .HasColumnName("c1");

                    b.Property<string>("C2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("C2")
                        .HasColumnName("c2");

                    b.HasKey("Id")
                        .HasName("p_app_index");

                    b.HasIndex("C1")
                        .IsUnique()
                        .HasDatabaseName("i_app_index_4d1f45");

                    b.HasIndex("C1", "C2")
                        .HasDatabaseName("i_app_index_d3bba8");

                    b.ToTable("app_index", null, t =>
                        {
                            t.HasComment("AppIndex");
                        });
                });

            modelBuilder.Entity("Model.Entities.AppTable", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateOnly?>("DateOnly")
                        .HasColumnType("date")
                        .HasColumnName("date_only");

                    b.Property<DateTime?>("DateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time");

                    b.Property<DateTimeOffset?>("DateTimeOffset")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_time_offset");

                    b.Property<decimal?>("Decimal")
                        .HasPrecision(5, 3)
                        .HasColumnType("numeric(5,3)")
                        .HasColumnName("decimal");

                    b.Property<int?>("Enum")
                        .HasColumnType("integer")
                        .HasColumnName("enum");

                    b.Property<int?>("Int")
                        .HasColumnType("integer")
                        .HasColumnName("int");

                    b.Property<long?>("Long")
                        .HasColumnType("bigint")
                        .HasColumnName("long");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("String")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("string");

                    b.Property<string>("StringJsonObjects")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("string_json_objects");

                    b.Property<string>("ValueJsonObject")
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json_object");

                    b.Property<string>("ValueJsonObjects")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json_objects");

                    b.HasKey("Id")
                        .HasName("p_app_table");

                    b.HasAlternateKey("String")
                        .HasName("a_app_table_274c57");

                    b.HasIndex("String")
                        .IsUnique()
                        .HasDatabaseName("i_app_table_274c57")
                        .HasFilter("string IS NOT NULL");

                    b.ToTable("app_table", null, t =>
                        {
                            t.HasComment("AppTable");

                            t.HasCheckConstraint("c_app_table_d5e7b8", "int > 0");
                        });
                });

            modelBuilder.Entity("Model.Entities.ClosureNode", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_closure_node");

                    b.ToTable("closure_node", null, t =>
                        {
                            t.HasComment("ClosureNode");
                        });
                });

            modelBuilder.Entity("Model.Entities.ClosurePath", b =>
                {
                    b.Property<long>("AncestorId")
                        .HasColumnType("bigint")
                        .HasColumnName("ancestor_id");

                    b.Property<long>("DescendantId")
                        .HasColumnType("bigint")
                        .HasColumnName("descendant_id");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.HasKey("AncestorId", "DescendantId")
                        .HasName("p_closure_path");

                    b.HasIndex("DescendantId")
                        .HasDatabaseName("i_closure_path_b1e295");

                    b.ToTable("closure_path", null, t =>
                        {
                            t.HasComment("ClosurePath");
                        });
                });

            modelBuilder.Entity("Model.Entities.HumanBody", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_date");

                    b.Property<int>("Color")
                        .HasColumnType("integer")
                        .HasColumnName("color");

                    b.Property<string>("HeadId")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("head_id");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<string>("Ulid")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ulid");

                    b.Property<int>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("p_human_body");

                    b.HasAlternateKey("Ulid")
                        .HasName("a_human_body_acb1a2");

                    b.HasIndex("HeadId")
                        .IsUnique()
                        .HasDatabaseName("i_human_body_0d4caa");

                    b.ToTable("human_body", null, t =>
                        {
                            t.HasComment("HumanBody");
                        });
                });

            modelBuilder.Entity("Model.Entities.HumanHead", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_date");

                    b.Property<int>("Color")
                        .HasColumnType("integer")
                        .HasColumnName("color");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<string>("Ulid")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ulid");

                    b.Property<int>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("p_human_head");

                    b.HasAlternateKey("Ulid")
                        .HasName("a_human_head_acb1a2");

                    b.ToTable("human_head", null, t =>
                        {
                            t.HasComment("HumanHead");
                        });
                });

            modelBuilder.Entity("Model.Entities.HumanLimb", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BodyId")
                        .HasColumnType("character varying(10)")
                        .HasColumnName("body_id");

                    b.Property<DateTime>("CheckDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_date");

                    b.Property<int>("Color")
                        .HasColumnType("integer")
                        .HasColumnName("color");

                    b.Property<string>("Remark")
                        .HasColumnType("text")
                        .HasColumnName("remark");

                    b.Property<string>("Ulid")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ulid");

                    b.Property<int>("Weight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("p_human_limb");

                    b.HasIndex("BodyId")
                        .HasDatabaseName("i_human_limb_394eba");

                    b.ToTable("human_limb", null, t =>
                        {
                            t.HasComment("HumanLimb");
                        });
                });

            modelBuilder.Entity("Model.Entities.LinkFirstContent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_link_first_content");

                    b.ToTable("link_first_content", null, t =>
                        {
                            t.HasComment("LinkFirstContent");
                        });
                });

            modelBuilder.Entity("Model.Entities.LinkSecondContent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_link_second_content");

                    b.ToTable("link_second_content", null, t =>
                        {
                            t.HasComment("LinkSecondContent");
                        });
                });

            modelBuilder.Entity("Model.Entities.LinkSubContent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("content");

                    b.Property<int>("LinkType")
                        .HasColumnType("integer")
                        .HasColumnName("link_type");

                    b.HasKey("Id")
                        .HasName("p_link_sub_content");

                    b.ToTable("link_sub_content", null, t =>
                        {
                            t.HasComment("LinkSubContent");
                        });

                    b.HasDiscriminator<int>("LinkType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Model.Entities.SubjectContent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("content");

                    b.Property<long>("ReferenceId")
                        .HasColumnType("bigint")
                        .HasColumnName("reference_id");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("integer")
                        .HasColumnName("reference_type");

                    b.HasKey("Id")
                        .HasName("p_subject_content");

                    b.HasIndex("ReferenceId", "ReferenceType")
                        .HasDatabaseName("i_subject_content_416b18");

                    b.ToTable("subject_content", (string)null);

                    b.HasDiscriminator<int>("ReferenceType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Model.Entities.SubjectFirst", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_subject_first");

                    b.ToTable("subject_first", null, t =>
                        {
                            t.HasComment("SubjectFirst");
                        });
                });

            modelBuilder.Entity("Model.Entities.SubjectSecond", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("p_subject_second");

                    b.ToTable("subject_second", null, t =>
                        {
                            t.HasComment("SubjectSecond");
                        });
                });

            modelBuilder.Entity("Model.Entities.VehicleBase", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<int>("VehicleCarType")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_car_type");

                    b.HasKey("Id")
                        .HasName("p_vehicle_base");

                    b.HasIndex("Type")
                        .HasDatabaseName("i_vehicle_base_682a0e");

                    b.ToTable("vehicle_base", null, t =>
                        {
                            t.HasCheckConstraint("c_vehicle_base_cb4012", "Type IN (1, 2)");
                        });

                    b.HasDiscriminator<int>("Type");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Model.Queries.EmptyDbSet", b =>
                {
                    b.ToTable("empty_db_set", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Model.Queries.FuncTableResult", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_func_table_result");

                    b.ToTable((string)null);

                    b.ToFunction("func_table");
                });

            modelBuilder.Entity("Model.Queries.FuncTableWithParamResult", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_func_table_with_param_result");

                    b.ToTable((string)null);

                    b.ToFunction("func_table_with_param");
                });

            modelBuilder.Entity("Model.Queries.KeyLessResult", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.ToTable("key_less_result", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Model.Queries.ViewResult", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_view_result");

                    b.ToTable((string)null);

                    b.ToView("view", (string)null);
                });

            modelBuilder.Entity("rel_link_first_sub_content", b =>
                {
                    b.Property<long>("link_first_content_id")
                        .HasColumnType("bigint")
                        .HasColumnName("link_first_content_id");

                    b.Property<long>("link_sub_content_id")
                        .HasColumnType("bigint")
                        .HasColumnName("link_sub_content_id");

                    b.HasKey("link_first_content_id", "link_sub_content_id")
                        .HasName("p_rel_link_first_sub_content");

                    b.HasIndex("link_sub_content_id")
                        .HasDatabaseName("i_rel_link_first_sub_content_d5f4dd");

                    b.ToTable("rel_link_first_sub_content", (string)null);
                });

            modelBuilder.Entity("rel_link_second_sub_content", b =>
                {
                    b.Property<long>("link_second_content_id")
                        .HasColumnType("bigint")
                        .HasColumnName("link_second_content_id");

                    b.Property<long>("link_sub_content_id")
                        .HasColumnType("bigint")
                        .HasColumnName("link_sub_content_id");

                    b.HasKey("link_second_content_id", "link_sub_content_id")
                        .HasName("p_rel_link_second_sub_content");

                    b.HasIndex("link_sub_content_id")
                        .HasDatabaseName("i_rel_link_second_sub_content_d5f4dd");

                    b.ToTable("rel_link_second_sub_content", (string)null);
                });

            modelBuilder.Entity("Model.Entities.LinkFirstSubContent", b =>
                {
                    b.HasBaseType("Model.Entities.LinkSubContent");

                    b.Property<string>("First")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Model.Entities.LinkSecondSubContent", b =>
                {
                    b.HasBaseType("Model.Entities.LinkSubContent");

                    b.Property<string>("Second")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("second");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Model.Entities.SubjectFirstContent", b =>
                {
                    b.HasBaseType("Model.Entities.SubjectContent");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Model.Entities.SubjectSecondContent", b =>
                {
                    b.HasBaseType("Model.Entities.SubjectContent");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Model.Entities.VehicleLargeCar", b =>
                {
                    b.HasBaseType("Model.Entities.VehicleBase");

                    b.Property<string>("CarName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("car_name");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("LargeCarName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("large_car_name");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("c_vehicle_base_cb4012", "Type IN (1, 2)");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Model.Entities.VehicleSmallCar", b =>
                {
                    b.HasBaseType("Model.Entities.VehicleBase");

                    b.Property<string>("CarName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("car_name");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("SmallCarName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("small_car_name");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("c_vehicle_base_cb4012", "Type IN (1, 2)");
                        });

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Model.Entities.ClosurePath", b =>
                {
                    b.HasOne("Model.Entities.ClosureNode", "Ancestor")
                        .WithMany("DescendantPaths")
                        .HasForeignKey("AncestorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_closure_path_e210a0");

                    b.HasOne("Model.Entities.ClosureNode", "Descendant")
                        .WithMany("AncestorPaths")
                        .HasForeignKey("DescendantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_closure_path_b1e295");

                    b.Navigation("Ancestor");

                    b.Navigation("Descendant");
                });

            modelBuilder.Entity("Model.Entities.HumanBody", b =>
                {
                    b.HasOne("Model.Entities.HumanHead", "HumanHead")
                        .WithOne("HumanBody")
                        .HasForeignKey("Model.Entities.HumanBody", "HeadId")
                        .HasPrincipalKey("Model.Entities.HumanHead", "Ulid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_human_body_0d4caa");

                    b.Navigation("HumanHead");
                });

            modelBuilder.Entity("Model.Entities.HumanLimb", b =>
                {
                    b.HasOne("Model.Entities.HumanBody", "HumanBody")
                        .WithMany("HumanLimbs")
                        .HasForeignKey("BodyId")
                        .HasPrincipalKey("Ulid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("f_human_limb_394eba");

                    b.Navigation("HumanBody");
                });

            modelBuilder.Entity("Model.Queries.FuncTableResult", b =>
                {
                    b.HasOne("Model.Entities.AnimalCat", null)
                        .WithOne("FuncTableResult")
                        .HasForeignKey("Model.Queries.FuncTableResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_func_table_result_animal_cat_id");
                });

            modelBuilder.Entity("Model.Queries.ViewResult", b =>
                {
                    b.HasOne("Model.Entities.AnimalCat", null)
                        .WithOne("ViewResult")
                        .HasForeignKey("Model.Queries.ViewResult", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_view_result_animal_cat_id");
                });

            modelBuilder.Entity("rel_link_first_sub_content", b =>
                {
                    b.HasOne("Model.Entities.LinkFirstContent", null)
                        .WithMany()
                        .HasForeignKey("link_first_content_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_rel_link_first_sub_content_9c6c37");

                    b.HasOne("Model.Entities.LinkFirstSubContent", null)
                        .WithMany()
                        .HasForeignKey("link_sub_content_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_rel_link_first_sub_content_d5f4dd");
                });

            modelBuilder.Entity("rel_link_second_sub_content", b =>
                {
                    b.HasOne("Model.Entities.LinkSecondContent", null)
                        .WithMany()
                        .HasForeignKey("link_second_content_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_rel_link_second_sub_content_8fa616");

                    b.HasOne("Model.Entities.LinkSecondSubContent", null)
                        .WithMany()
                        .HasForeignKey("link_sub_content_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_rel_link_second_sub_content_d5f4dd");
                });

            modelBuilder.Entity("Model.Entities.SubjectFirstContent", b =>
                {
                    b.HasOne("Model.Entities.SubjectFirst", "Subject")
                        .WithMany("Contents")
                        .HasForeignKey("ReferenceId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("d_subject_first_content_reference_id");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Model.Entities.SubjectSecondContent", b =>
                {
                    b.HasOne("Model.Entities.SubjectSecond", "Subject")
                        .WithMany("Contents")
                        .HasForeignKey("ReferenceId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired()
                        .HasConstraintName("d_subject_second_content_reference_id");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("Model.Entities.AnimalCat", b =>
                {
                    b.Navigation("FuncTableResult")
                        .IsRequired();

                    b.Navigation("ViewResult")
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Entities.ClosureNode", b =>
                {
                    b.Navigation("AncestorPaths");

                    b.Navigation("DescendantPaths");
                });

            modelBuilder.Entity("Model.Entities.HumanBody", b =>
                {
                    b.Navigation("HumanLimbs");
                });

            modelBuilder.Entity("Model.Entities.HumanHead", b =>
                {
                    b.Navigation("HumanBody")
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Entities.SubjectFirst", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("Model.Entities.SubjectSecond", b =>
                {
                    b.Navigation("Contents");
                });
#pragma warning restore 612, 618
        }
    }
}
